# NumPy Basics

For this course, we will be using NumPy extensively for coding components. This tutorial intends to give everyone a brief overview of what we can do with NumPy.

NumPy is a numerical computing library for Python. "Nearly every scientist working in Python draws on the power of NumPy". It is widely used in research and the industry where machine learning, data processing, data analytics, etc. are required.

Reference: https://numpy.org/doc/2.1/

In [2]:
# first install numpy if not already installed
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np

## N-D Arrays
NumPy's main object is the homogeneous multidimensional array. In other words, it is a "table" consisting elements of *same type* (usually numbers) that can be indexed by integers. In NumPy, dimensions are known as *axes*. For this course, you will mostly deal with dimensions up to 3.

In [4]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

print(a)

# This checks the type of the array
print(a.dtype)

# This checks the dimensions (shape) of the array
print(a.shape)

# This checks the number of dimensions
print(a.ndim)

# This checks the total number of entries in the array
print(a.size)

[[1 2 3]
 [2 3 4]]
int32
(2, 3)
2
6


## Array Creation

In [5]:
# Create zero array
zero_array = np.zeros(shape=(5, 2))

# Create one array
one_array = np.ones(shape=(5, 2))

# Creating arrays filled with specific values
fill_array = np.full(shape=(5, 2), fill_value=10, dtype=np.float32)

# Create Identity matrix
identity = np.eye(10)

# Create an array from 1 to 10
seq = np.arange(1, 11)

# Create an array from 0 to 1 spaced by 0.1
seq_2 = np.arange(0, 1.1, 0.1)

print(zero_array)
print(one_array)
print(fill_array)
print(identity)
print(seq)
print(seq_2)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[ 1  2  3  4  5  6  7  8  9 10]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


## Shape Manipulation and Indexing
### 2D arrays

In [6]:
seq = np.arange(1, 13)
print(seq)

# Reshape to a 2D array of shape (4, 3)
# Note that the new shape needs to match the number of elements in the array
reshaped_seq = seq.reshape((4, 3))
print(reshaped_seq)

# Transpose a 2D array
reshaped_seq = reshaped_seq.T
print(reshaped_seq)

# Take first row, second column of reshaped_seq
print(reshaped_seq[0, 1])

# Take first row
print(reshaped_seq[0])

# Take third column
print(reshaped_seq[:, 2])

# Take columns 0, 2, 3 of all rows
print(reshaped_seq[:, [0, 2, 3]])

# You can take elements based on conditions (advance indexing)
# Take elements greater than 4 (then flatten the array)
print(reshaped_seq[reshaped_seq > 4])

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
4
[ 1  4  7 10]
[7 8 9]
[[ 1  7 10]
 [ 2  8 11]
 [ 3  9 12]]
[ 7 10  5  8 11  6  9 12]


### Higher Dimensional Arrays
It is important to get comfortable with multidimensional arrays with dimension > 2.
In this case, we will refer each dimension using index notation
```
(d_0, d_1, d_2, ..., d_n)
```

Please make sure you understand how these work! You will be able to write elegant and efficient code with this!

In [7]:
# Reshape to a 3D array of shape (2, 2, 3)
reshaped_seq = seq.reshape((2, 2, 3))
print(reshaped_seq)

# Transpose an array. You can consider this as swapping axes
# Swap first and last axes
reshaped_seq = reshaped_seq.transpose(2, 1, 0)
print(reshaped_seq)

# Take first d_0
print(reshaped_seq[0])

# Take first d_1
print(reshaped_seq[:, 0])

# Take first d_2
print(reshaped_seq[..., 0])

# Take third d_0 and second d_2
print(reshaped_seq[2, :, 1])

# You can take elements based on conditions (advance indexing)
# Take elements greater than 4
print(reshaped_seq[reshaped_seq > 4])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]
[[ 1  7]
 [ 4 10]]
[[1 7]
 [2 8]
 [3 9]]
[[1 4]
 [2 5]
 [3 6]]
[ 9 12]
[ 7 10  8  5 11  9  6 12]


## Math Operations

In [10]:
a = np.arange(0, 10).reshape(5, 2)
b = np.arange(0, 1.0, 0.1).reshape(5, 2)

# Element-wise addition
print(a + b)

# Element-wise multiplication
print(a * b)

# Element-wise division
print(a / b)

# Element-wise exponential
print(a ** b)

# Matrix multiplication
print(a @ b.T)
print(np.matmul(a, b.T))

[[0.  1.1]
 [2.2 3.3]
 [4.4 5.5]
 [6.6 7.7]
 [8.8 9.9]]
[[0.  0.1]
 [0.4 0.9]
 [1.6 2.5]
 [3.6 4.9]
 [6.4 8.1]]
[[nan 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]]
[[1.         1.        ]
 [1.14869835 1.39038917]
 [1.74110113 2.23606798]
 [2.93015605 3.90452878]
 [5.27803164 7.22467406]]
[[ 0.1  0.3  0.5  0.7  0.9]
 [ 0.3  1.3  2.3  3.3  4.3]
 [ 0.5  2.3  4.1  5.9  7.7]
 [ 0.7  3.3  5.9  8.5 11.1]
 [ 0.9  4.3  7.7 11.1 14.5]]
[[ 0.1  0.3  0.5  0.7  0.9]
 [ 0.3  1.3  2.3  3.3  4.3]
 [ 0.5  2.3  4.1  5.9  7.7]
 [ 0.7  3.3  5.9  8.5 11.1]
 [ 0.9  4.3  7.7 11.1 14.5]]


C:\Users\yqhua\AppData\Local\Temp\ipykernel_480\2116182931.py:11: RuntimeWarning: invalid value encountered in divide
  print(a / b)


### Higher Dimensional Arrays
Most operations are the same in higher dimensional arrays. But you might be curious about how we can perform matrix multiplcation (if we can).

In [14]:
a = np.arange(0, 24).reshape(4, 2, 3)
b = np.arange(0, 2.4, 0.1).reshape(4, 2, 3)

# You can perform batch matrix multiplcation
# This treats the 3D arrays as d_0 2D arrays, and perform matrix multiplication for each i = 1, ..., d_0
print(a @ b.transpose(0, 2, 1))
print(np.matmul(a, b.transpose(0, 2, 1))) # the permutation of axes specifies how to transpose

[[[  0.5   1.4]
  [  1.4   5. ]]

 [[ 14.9  21.2]
  [ 21.2  30.2]]

 [[ 50.9  62.6]
  [ 62.6  77. ]]

 [[108.5 125.6]
  [125.6 145.4]]]
[[[  0.5   1.4]
  [  1.4   5. ]]

 [[ 14.9  21.2]
  [ 21.2  30.2]]

 [[ 50.9  62.6]
  [ 62.6  77. ]]

 [[108.5 125.6]
  [125.6 145.4]]]


## Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [15]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [16]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

y = x + vv  # Add x and vv elementwise
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [17]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Here are some applications of broadcasting:

In [18]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [19]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [20]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


## Some other Tricks

In [ ]:
a = np.arange(10)
b = np.arange(20).reshape(2, 10, 1)

# Say you want to do matrix multiplcation between b and a,
# but clearly a is an axis short. We can "expand dimension" quickly
print(b @ a.reshape((1, 10)))
print(b @ a[None, ...])

# If you want to apply a vector of exponents onto a single scalar
a = 10
b = np.arange(3)
print(a ** b)

# Create one-hot encoding
# Say you want a one-hot encoding such that vector is in R^5, and the fourth element is 1
print(np.eye(5)[3])

## Common types
Depending on the situation, you may prefer one type over the other. Here is the list of most commonly used types:
```
np.uint8
np.int32
np.int64
np.float32
np.float64
np.bool
```

Understanding which type to use based on the context is important as you deal with large datasets. Imagine a 84x84 RGB image (i.e. `shape=(84, 84, 3)`). Storing 10000 images in `np.float64` will take up approximately 1.577GB of memory, whereas `np.uint8` only takes up approximately 197MB.

In [13]:
# You can enforce the type of a numpy array
a = np.array([[1, 2, 3],
              [2, 3, 4]],
             np.float32)

print(a)
print(a.dtype)

[[1. 2. 3.]
 [2. 3. 4.]]
float32


## NaN and Inf
For different scenarios, you may encounter `nan` (Not a Number) and `inf` (Infinity) values.
`nan` usually occurs when your function input is not part of the function domain (e.g. log of a negative value).
`inf` usually occurs when your function computes a number that is too large (e.g. e^x).

In [12]:
print(np.log(-1))
print(np.array(0.) / np.array(0.))
print(np.exp(1000))

nan
nan
inf


C:\Users\yqhua\AppData\Local\Temp\ipykernel_480\204965167.py:1: RuntimeWarning: invalid value encountered in log
  print(np.log(-1))
C:\Users\yqhua\AppData\Local\Temp\ipykernel_480\204965167.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0.) / np.array(0.))
C:\Users\yqhua\AppData\Local\Temp\ipykernel_480\204965167.py:3: RuntimeWarning: overflow encountered in exp
  print(np.exp(1000))


# Final Words
Read [here](https://numpy.org/doc/2.1/user/quickstart.html) for more tutorials! They are short and concise